spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        events-in:
          destination: event
          contentType: application/json
        events-out:
          destination: event
          contentType: application/json